server:
  port: 8085
  ssl:
    key-store: classpath:www-tangle-ink-0901133425.pfx
    key-store-password: dHzfY90f
    key-store-type: PKCS12
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://39.101.188.252:3306/yami_shops?userSSL=false
    username: root
    password: 597130788
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1
  cache:
    type: redis
    redis:
      cache-null-values: true
  redis:
    redisson:
      config: classpath:redisson.yml
logging:
  config: classpath:log4j2_dev.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

